name: zed_settings_sync_app

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tray_manager: ^0.5.2
  window_manager: ^0.5.1
  github: ^9.25.0
  objectbox: ^5.1.0
  path_provider: ^2.1.5
  forui: ^0.17.0
  file_picker: ^10.3.8
  build_runner: ^2.10.4
  objectbox_flutter_libs: any
  flutter_shell: ^0.0.2
  launch_at_startup: ^0.5.1
  package_info_plus: ^9.0.0
  msix: ^3.16.12

dependency_overrides:
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  objectbox_generator: any
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/tray_icon.png
    - assets/icons/tray_icon.ico
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

msix_config:
  display_name: zed_settings_sync_app
  identity_name: com.maciejdudek.zedsettingssync
  msix_version: 1.0.0.0
  logo_path: C:\Users\maciej\OneDrive\Pulpit\Nowy folder (3)\nxtlvl-group\zed-settings-sync-app\assets\icons\app_icon.png
